### ISSUE TITLE
E-2403: mail_engine: timed out obtaining a reference on /var/lib/gromox/user/8/9

### ISSUE THREAD

**Issue by amaccuish** [grommunio/gromox#74]
Somewhere between 2.15 and 2.16 IMAP has stopped working with the following error from midb. I've checked the directory permissions, on SUSE midb files seem to need to be owned by gromox:grommunio, chmod is 660.

Running `echo ".dump" | sqlite3 midb.sqlite3 | sqlite3 midb.sqlite3` hasn't worked, nor the steps described here: https://community.grommunio.com/d/1048-midb-what-are-these-databases-for-and-how-to-regenerate-the-midb

Web/ActiveSync, presumably anything not running through MIDB, is working. Filesystem is R/W, journal files are created successfully for example.

Unfortunately can't use EWS as a work around since it only syncs my mails up until 2020, will file separate bug report for that.

I've turned up the logging on midb for you below.

> 2023-11-12 10:56:47.312605]: system: MIDB is now running
[2023-11-12 10:58:49.014249]: > sqlite3_prep(SELECT `config_value` FROM `configurations` WHERE `config_id`=10)
[2023-11-12 10:58:49.016355]: > sqlite3_exec(PRAGMA foreign_keys=ON)
[2023-11-12 10:58:49.016462]: > sqlite3_exec(DELETE FROM mapping)
[2023-11-12 10:58:49.053403]: Running sync_mailbox for /var/lib/gromox/user/8/9
[2023-11-12 10:58:49.071243]: > sqlite3_exec(BEGIN TRANSACTION)
[2023-11-12 10:58:49.071584]: > sqlite3_exec(CREATE TABLE folders (folder_id INTEGER PRIMARY KEY,parent_fid INTEGER,display_name TEXT,commit_max INTEGER))
[2023-11-12 10:58:49.071720]: > sqlite3_prep(INSERT INTO folders (folder_id, parent_fid, display_name, commit_max) VALUES (?, ?, ?, ?))
[2023-11-12 10:58:49.071857]: sync_mailbox /var/lib/gromox/user/8/9 fld 15 skipped: PR_CONTAINER_CLASS not IPF.Note
[2023-11-12 10:58:49.071981]: sync_mailbox /var/lib/gromox/user/8/9 fld 16 skipped: PR_CONTAINER_CLASS not IPF.Note
[2023-11-12 10:58:49.072057]: sync_mailbox /var/lib/gromox/user/8/9 fld 17 skipped: PR_CONTAINER_CLASS not IPF.Note
[2023-11-12 10:58:49.072140]: sync_mailbox /var/lib/gromox/user/8/9 fld 18 skipped: PR_CONTAINER_CLASS not IPF.Note
[2023-11-12 10:58:49.072223]: sync_mailbox /var/lib/gromox/user/8/9 fld 19 skipped: PR_CONTAINER_CLASS not IPF.Note
[2023-11-12 10:58:49.072335]: sync_mailbox /var/lib/gromox/user/8/9 fld 20 skipped: PR_ATTR_HIDDEN=1
[2023-11-12 10:58:49.072428]: sync_mailbox /var/lib/gromox/user/8/9 fld 21 skipped: PR_ATTR_HIDDEN=1
[2023-11-12 10:58:49.072526]: sync_mailbox /var/lib/gromox/user/8/9 fld 22 skipped: PR_ATTR_HIDDEN=1
[2023-11-12 10:58:49.072604]: sync_mailbox /var/lib/gromox/user/8/9 fld 29 skipped: PR_ATTR_HIDDEN=1
[2023-11-12 10:58:49.072698]: sync_mailbox /var/lib/gromox/user/8/9 fld 2246081 skipped: PR_CONTAINER_CLASS not IPF.Note
[2023-11-12 10:58:49.072785]: sync_mailbox /var/lib/gromox/user/8/9 fld 2256081 skipped: PR_CONTAINER_CLASS not IPF.Note
[2023-11-12 10:58:49.072889]: > sqlite3_exec(COMMIT TRANSACTION)
[2023-11-12 10:58:49.072978]: > sqlite3_exec(BEGIN TRANSACTION)
[2023-11-12 10:58:49.073072]: > sqlite3_prep(SELECT folder_id, parent_fid, commit_max FROM folders)
[2023-11-12 10:58:49.073185]: > sqlite3_prep(SELECT folder_id, parent_fid, commit_max, name FROM folders WHERE folder_id=?)
[2023-11-12 10:58:49.073278]: > sqlite3_prep(INSERT INTO folders (folder_id, parent_fid, commit_max, name) VALUES (?, ?, ?, ?))
[2023-11-12 10:58:49.073352]: > sqlite3_prep(SELECT parent_fid, display_name FROM folders WHERE folder_id=?)
[2023-11-12 10:58:49.073421]: Running sync_contents for /var/lib/gromox/user/8/9, folder 13
[2023-11-12 10:58:51.554179]: > sqlite3_prep(SELECT uidnext FROM folders WHERE folder_id=13)
[2023-11-12 10:58:51.554978]: > sqlite3_exec(BEGIN TRANSACTION)
[2023-11-12 10:58:51.555135]: > sqlite3_exec(CREATE TABLE messages (message_id INTEGER PRIMARY KEY,mid_string TEXT,mod_time INTEGER,message_flags INTEGER,received INTEGER))
[2023-11-12 10:58:51.555404]: > sqlite3_prep(INSERT INTO messages (message_id, mid_string, mod_time, message_flags, received) VALUES (?, ?, ?, ?, ?))
[2023-11-12 10:58:51.620424]: > sqlite3_exec(COMMIT TRANSACTION)
[2023-11-12 10:58:51.620635]: > sqlite3_prep(SELECT COUNT(*) FROM messages)
[2023-11-12 10:58:51.620710]: > sqlite3_prep(SELECT message_id, mid_string, mod_time, message_flags, received FROM messages)
[2023-11-12 10:58:51.620774]: > sqlite3_prep(SELECT message_id, mid_string, mod_time, unsent, read FROM messages WHERE message_id=?)
[2023-11-12 10:58:51.620829]: > sqlite3_prep(INSERT INTO messages (message_id, folder_id, mid_string, mod_time, uid, unsent, read, subject, sender, rcpt, size, received) VALUES (?, 13, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?))
[2023-11-12 10:58:51.622292]: > sqlite3_prep(UPDATE messages SET unsent=?, read=? WHERE message_id=?)
[2023-11-12 10:58:51.624124]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 512/37881
[2023-11-12 10:58:51.624856]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 1024/37881
[2023-11-12 10:58:51.628376]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 1536/37881
[2023-11-12 10:58:51.635109]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 2048/37881
[2023-11-12 10:58:51.636850]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 2560/37881
[2023-11-12 10:58:51.637560]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 3072/37881
[2023-11-12 10:58:51.638244]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 3584/37881
[2023-11-12 10:58:51.638898]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 4096/37881
[2023-11-12 10:58:51.639579]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 4608/37881
[2023-11-12 10:58:51.640315]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 5120/37881
[2023-11-12 10:58:51.642800]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 5632/37881
[2023-11-12 10:58:51.647865]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 6144/37881
[2023-11-12 10:58:51.648001]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 6656/37881
[2023-11-12 10:58:51.648080]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 7168/37881
[2023-11-12 10:58:51.648121]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 7680/37881
[2023-11-12 10:58:51.648199]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 8192/37881
[2023-11-12 10:58:51.648268]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 8704/37881
[2023-11-12 10:58:51.648609]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 9216/37881
[2023-11-12 10:58:51.649293]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 9728/37881
[2023-11-12 10:58:51.650025]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 10240/37881
[2023-11-12 10:58:51.650699]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 10752/37881
[2023-11-12 10:58:51.651353]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 11264/37881
[2023-11-12 10:58:51.651971]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 11776/37881
[2023-11-12 10:58:51.655012]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 12288/37881
[2023-11-12 10:58:51.660867]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 12800/37881
[2023-11-12 10:58:51.666933]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 13312/37881
[2023-11-12 10:58:51.674115]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 13824/37881
[2023-11-12 10:58:51.680752]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 14336/37881
[2023-11-12 10:58:51.683146]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 14848/37881
[2023-11-12 10:58:51.691189]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 15360/37881
[2023-11-12 10:58:51.691581]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 15872/37881
[2023-11-12 10:58:51.692080]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 16384/37881
[2023-11-12 10:58:51.692534]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 16896/37881
[2023-11-12 10:58:51.693015]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 17408/37881
[2023-11-12 10:58:51.693482]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 17920/37881
[2023-11-12 10:58:51.693940]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 18432/37881
[2023-11-12 10:58:51.695665]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 18944/37881
[2023-11-12 10:58:51.715557]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 19456/37881
[2023-11-12 10:58:51.717523]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 19968/37881
[2023-11-12 10:58:51.717895]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 20480/37881
[2023-11-12 10:58:51.718072]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 20992/37881
[2023-11-12 10:58:51.718555]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 21504/37881
[2023-11-12 10:58:51.719449]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 22016/37881
[2023-11-12 10:58:51.720082]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 22528/37881
[2023-11-12 10:58:51.720571]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 23040/37881
[2023-11-12 10:58:51.721051]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 23552/37881
[2023-11-12 10:58:51.721533]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 24064/37881
[2023-11-12 10:58:51.722020]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 24576/37881
[2023-11-12 10:58:51.722498]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 25088/37881
[2023-11-12 10:58:51.722986]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 25600/37881
[2023-11-12 10:58:51.723765]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 26112/37881
[2023-11-12 10:58:51.732949]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 26624/37881
[2023-11-12 10:58:51.733134]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 27136/37881
[2023-11-12 10:58:51.733591]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 27648/37881
[2023-11-12 10:58:51.734047]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 28160/37881
[2023-11-12 10:58:51.734785]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 28672/37881
[2023-11-12 10:58:51.742122]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 29184/37881
[2023-11-12 10:58:51.744660]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 29696/37881
[2023-11-12 10:58:51.751383]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 30208/37881
[2023-11-12 10:58:51.751644]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 30720/37881
[2023-11-12 10:58:51.751736]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 31232/37881
[2023-11-12 10:58:51.751812]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 31744/37881
[2023-11-12 10:58:51.753280]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 32256/37881
[2023-11-12 10:58:51.753469]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 32768/37881
[2023-11-12 10:58:51.754274]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 33280/37881
[2023-11-12 10:58:51.754471]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 33792/37881
[2023-11-12 10:58:51.778767]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 34304/37881
[2023-11-12 10:58:51.779535]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 34816/37881
[2023-11-12 10:58:51.779690]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 35328/37881
[2023-11-12 10:58:51.781367]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 35840/37881
[2023-11-12 10:58:51.781474]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 36352/37881
[2023-11-12 10:58:51.786139]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 36864/37881
[2023-11-12 10:58:51.788963]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 37376/37881
[2023-11-12 10:58:51.868515]: sync_contents /var/lib/gromox/user/8/9 fld 13 progress: 37881/37881
[2023-11-12 10:58:51.868823]: > sqlite3_prep(SELECT message_id FROM messages WHERE folder_id=13)
[2023-11-12 10:58:51.868932]: > sqlite3_prep(SELECT message_id FROM messages WHERE message_id=?)
[2023-11-12 10:58:51.935238]: > sqlite3_exec(UPDATE folders SET uidnext=37881 WHERE folder_id=13)
[2023-11-12 10:58:51.935781]: > sqlite3_exec(UPDATE folders SET sort_field=0 WHERE folder_id=13)
[2023-11-12 10:58:51.936919]: > sqlite3_exec(UPDATE folders SET commit_max=133442564639272469 WHERE folder_id=13)
[2023-11-12 10:58:51.943999]: > sqlite3_prep(SELECT folder_id FROM folders)
[2023-11-12 10:58:51.944196]: > sqlite3_prep(SELECT folder_id FROM folders WHERE folder_id=?)
[2023-11-12 10:58:51.944317]: > sqlite3_exec(COMMIT TRANSACTION)
[2023-11-12 10:58:52.026129]: Ended sync_mailbox for /var/lib/gromox/user/8/9
[2023-11-12 10:58:52.026380]: > sqlite3_prep(SELECT folder_id, name FROM folders)
[2023-11-12 10:58:52.047437]: > sqlite3_prep(SELECT name FROM folders WHERE unsub=0)
[2023-11-12 10:58:52.048303]: > sqlite3_prep(SELECT folder_id, name FROM folders)
[2023-11-12 10:58:52.068002]: > sqlite3_prep(SELECT folder_id, uidnext FROM folders WHERE name=?)
[2023-11-12 10:58:52.068358]: > sqlite3_prep(SELECT count(message_id) FROM messages WHERE folder_id=13)
[2023-11-12 10:58:52.070752]: > sqlite3_prep(SELECT count(message_id) FROM messages WHERE folder_id=13 AND read=0)
[2023-11-12 10:58:52.072722]: > sqlite3_prep(SELECT count(message_id) FROM messages WHERE folder_id=13 AND recent=0)
[2023-11-12 10:58:52.074496]: > sqlite3_prep(SELECT min(idx) FROM messages WHERE folder_id=13 AND read=0)
[2023-11-12 10:58:52.092911]: > sqlite3_prep(SELECT folder_id FROM folders WHERE name=?)
[2023-11-12 10:58:52.093132]: > sqlite3_prep(SELECT folder_id, sort_field FROM folders WHERE name=?)
[2023-11-12 10:58:52.093210]: > sqlite3_prep(SELECT message_id FROM messages WHERE folder_id=13 ORDER BY uid)
[2023-11-12 10:58:52.093339]: > sqlite3_prep(UPDATE messages SET idx=? WHERE message_id=?)
[2023-11-12 11:00:52.273949]: E-2403: mail_engine: timed out obtaining a reference on /var/lib/gromox/user/8/9
[2023-11-12 11:00:52.274687]: < P-FDDT /var/lib/gromox/user/8/9 inbox
[2023-11-12 11:00:52.274687]: > FALSE 2

**Comment by jengelh** [comment]
> Running `echo ".dump" | sqlite3 midb.sqlite3 | sqlite3 midb.sqlite3` hasn't worked

Modifying the same database you are reading from is not supposed to work.

>nor here https://community.grommunio.com/d/1048
>> [2023-11-12 11:00:52.273949]: E-2403: mail_engine: timed out obtaining a reference on /var/lib/gromox/user/8/9

Because recreating the database will do exactly nothing for a _contention_ issue (E-2403).

**Comment by amaccuish** [comment]
@jengelh I shutdown midb and imap, dumped the database to a separate file, then moved it, then started the services back up. I abbreviated the command above.

> Because recreating the database will do exactly nothing for a contention issue (E-2403).
I was assuming it couldn't obtain a lock possibly because a previous process crashed and the lock was stuck.

**Comment by amaccuish** [comment]
Closing, seems fixed in gromox-2.17.88.da6bc72-lp155.28.1.x86_64, thank you!

**Comment by jengelh** [comment]
There was a bottleneck wherein opening a folder could take up to {number of messages × 0.003 sec} (time on my machine, anyway) because midb refreshed an index.
If, at the same time, a second client tried to open the folder as well, it would wait—but timeout after 60s, which means that, opening the folder could fail if it had >20k messages.

d741887fb , 103c678eb

**Comment by amaccuish** [comment]
Thank you for the speedy fix!

**Comment by deajan** [comment]
I still get lots errors like the following on my personal server running gromox-3.1.113.g937e7f8-lp156.36.1.x86_64
```
oct. 13 11:34:42 email gromox-midb[1693]: E-2403: mail_engine: timed out obtaining a reference on /var/lib/gromox/user/domain.tld/infra
```

I noticed that this happens on two fairly big mailboxes (automatic emails sent X times a day, mboxes with 250K emails per mbox), which are accessed by multiple IMAP clients.
Is there any chance that ther's still a bottleneck, or should I try to rule out other things that could touch the midb sql file ?
